### ISSUE TITLE
Fails with `Error: cannot establish a connection`

### ISSUE THREAD

**Issue by kubark42** [giannisterzopoulos/scribd-dl#23]
* scribd-dl version: 0.4.5
* Python version: 3
* Operating System: macOS

### Description

Script fails to download file, returns `Error: cannot establish a connection.` This seems to be independent of the URL.

### What I Did

```
python3 scribd_dl.py https://www.scribd.com/document/90403141/Social-Media-Strategy
[90403141]  Visiting requested url
[90403141]  Error: cannot establish a connection.
```

**Comment by ferege** [comment]
the same error 
Error: cannot establish a connection.

**Comment by julianobn** [comment]
I've got the same error:
```
$ scribd-dl https://pt.scribd.com/document/...
[317707999]  Visiting requested url
[317707999]  Error: cannot establish a connection.
```

**Comment by svenk** [comment]
Same for me. Apparently it tries to connect to `http://127.0.0.1:41463` which seems non-logical to me (this is the loopback interface).

**Comment by dimyself** [comment]
Same for me...Anyone any ideas on this?

`Message: '%s://%s:%s "%s %s %s" %s %s'
Arguments: ('http', '127.0.0.1', 34903, 'POST', '/session/ed477fe316c96e7ee24bcd27d351d7df/element', 'HTTP/1.1', 404, 267)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 436, in format
    return self._format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 432, in _format
    return self._fmt % record.__dict__
KeyError: 'label'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 667, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 636, in formatMessage
    return self._style.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 438, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'label'
Call stack:
`

**Comment by giorgiopagnoni** [comment]
same...

**Comment by kamalguptas** [comment]
anyone got solution ????got same error

**Comment by giorgio-denunzio** [comment]
Same problem. I tried with one of the examples given by the Author, verbose mode on. I'll examine the output.
