### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_page_load_timeout'

### ISSUE THREAD

**Issue by peterswanson** [giannisterzopoulos/scribd-dl#25]
* scribd-dl version: 0.4.5
* Python version: 3.7
* Operating System: Windows 10

### Description

I am trying to use the DL on a scribd page (https://www.scribd.com/doc/298463647/She-Loves-Me) 
using this command:  scribd-dl https://www.scribd.com/doc/298463647/She-Loves-Me
but I keep getting this error:

DevTools listening on ws://127.0.0.1:52702/devtools/browser/8db07dd0-447f-4390-b361-995020254a1d
[error]  Chromedriver needs to be in assets directory or in PATH
Traceback (most recent call last):
  File "c:\users\peterswanson\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\peterswanson\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\peterswanson\AppData\Local\Programs\Python\Python37\Scripts\scribd-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\peterswanson\appdata\local\programs\python\python37\lib\site-packages\scribd_dl\__init__.py", line 41, in main
    scribd.download(URLS)
  File "c:\users\peterswanson\appdata\local\programs\python\python37\lib\site-packages\scribd_dl\scribd_dl.py", line 140, in download
    self.start_browser()
  File "c:\users\peterswanson\appdata\local\programs\python\python37\lib\site-packages\scribd_dl\scribd_dl.py", line 106, in start_browser
    self.driver.set_page_load_timeout(self.LOAD_TIME)
AttributeError: 'NoneType' object has no attribute 'set_page_load_timeout'

I suspect that this DL is not uptodate with the latest chrome and sellelim. What is the best way to procede?

**Comment by Edern76** [comment]
I know it's been two years but here's the solution I found in case someone gets here via Google : you need to download [chromedriver](https://sites.google.com/a/chromium.org/chromedriver/downloads) and put it in a directory that is in your system's PATH.

However the download still fails with the same error as in issue #23
