### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_page_load_timeout'

### ISSUE THREAD

**Issue by SudipBayen** [giannisterzopoulos/scribd-dl#28]
* scribd-dl version: 0.4.5
* Python version: Python 3.8.5
* Operating System: Ubuntu 20.10

### This Was My Command

```
scribd-dl https://www.scribd.com/document/440444961/A-Document-Name
```

### Error, That I Was Found

```
[error]  Chromedriver needs to be in assets directory or in PATH
Traceback (most recent call last):
  File "/usr/local/bin/scribd-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/scribd_dl/__init__.py", line 41, in main
    scribd.download(URLS)
  File "/usr/local/lib/python3.8/dist-packages/scribd_dl/scribd_dl.py", line 140, in download
    self.start_browser()
  File "/usr/local/lib/python3.8/dist-packages/scribd_dl/scribd_dl.py", line 106, in start_browser
    self.driver.set_page_load_timeout(self.LOAD_TIME)
AttributeError: 'NoneType' object has no attribute 'set_page_load_timeout'

**Comment by KalimAmzad** [comment]
I faced the same issue. Any solution?
